[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
serde = "1.0.219"
sqlx = { version = "0.8.6", features = ["postgres", "runtime-async-std-native-tls"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
